require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - db/schema.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - config/environments/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false
