require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - db/schema.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - config/environments/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Style/Documentation:
  Enabled: false
